using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using SPP4Test;

namespace SPP4Test.Test
{
    [TestClass]
    public class ConsoleOutputTest
    {
        private ConsoleOutput consoleOutputTestInstance; 

        [TestInitialize]
        public void TestInitialize()
        {
            consoleOutputTestInstance = new ConsoleOutput();
        }

        [TestMethod]
        public void MainTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}