using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using FooBar.Foo;

namespace FooBar.Foo.Test
{
    [TestClass]
    public class FooTest
    {
        private Foo fooTestInstance; 

        [TestInitialize]
        public void TestInitialize()
        {
            var p1 = default(int);
            var p2 = default(double);
            fooTestInstance = new Foo(p1, p2);
        }

        [TestMethod]
        public void GetIntTest()
        {
            int actual = fooTestInstance.GetInt(); 

            var expected = default(int);
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void sumTest()
        {
            var param1 = default(int);
            var param2 = default(double); 

            Assert.Fail("autogenerated");
        }
    }
}